### ISSUE TITLE
Show page generator doesn't include "previous" post link.

### ISSUE THREAD

**Issue by bbugh** [buttercms/buttercms-rails#2]
The `posts/show.html.erb` template only generates the "next" page link.

https://github.com/ButterCMS/buttercms-rails/blob/7f6ca859629de86183133a9896a5590c5e3bdeeb/lib/generators/templates/app/views/buttercms/posts/show.html.erb#L23-L26

The controller is setting `@previous_post` but then it's not used. Seems to be missing this in the generator:

```erb
  <!-- Link to Previous Post --> 
  <% if @previous_post %>
    <%= link_to @previous_post.title, buttercms_post_path(@previous_post.slug), :title => @previous_post.title %>
  <% end %>
```

**Comment by jakelumetta** [comment]
Resolved in https://github.com/ButterCMS/buttercms-rails/commit/e1a76a6218fb8e2e47ee59c7368771829f1f6caf
