### ISSUE TITLE
buttercms-ruby dependency is out of date

### ISSUE THREAD

**Issue by bbugh** [buttercms/buttercms-rails#3]
The buttercms-ruby gem is currently locked to `~> 1.3.1`, but the latest version is `1.7.0`. I am unable to upgrade the buttercms-ruby gem to get the changes in https://github.com/ButterCMS/buttercms-ruby/pull/14 without this change. I don't know the full implications of upgrading, so I'm making an issue instead.

**Comment by jakelumetta** [comment]
Resolved in https://github.com/ButterCMS/buttercms-rails/commit/df2f8b6f55bc17e92e8ae860784c288b4f4dfd99

**Comment by jakelumetta** [comment]
@bbugh Please upgrade to https://rubygems.org/gems/buttercms-rails/versions/1.2.3

**Comment by bbugh** [comment]
Thank you @jakelumetta!
