### ISSUE TITLE
Can't Use Latest buttercms-ruby library

### ISSUE THREAD

**Issue by HamptonMakes** [buttercms/buttercms-rails#4]
https://github.com/ButterCMS/buttercms-rails/blob/df2f8b6f55bc17e92e8ae860784c288b4f4dfd99/buttercms-rails.gemspec#L18

This should like be `>=`

**Comment by ViolanteCodes** [comment]
Closed with https://github.com/ButterCMS/buttercms-rails/commit/c623c9baf368206247d6389d0f32aec2b8b36dfd
