### ISSUE TITLE
Net::OpenTimeout error while accessing buttercms api 

### ISSUE THREAD

**Issue by usmanasif7** [buttercms/buttercms-rails#5]
Hi,
I'm using this gem to integrate ButterCMS in my rails app but sometimes on local setup I get this error.
I'm afraid I might get it in production as well. Can you please look into this.
Thanks.
<img width="1071" alt="Screenshot 2021-03-22 at 4 23 43 PM" src="https://user-images.githubusercontent.com/76130944/111982611-67872580-8ac6-11eb-92f1-49692dfdbeeb.png">

**Comment by jakelumetta** [comment]
Hi - please reach out to our support team (chat on our website) and we can help troubleshoot.
