### ISSUE TITLE
Update buttercms-ruby dependency

### ISSUE THREAD

**Issue by mark-kraemer** [buttercms/buttercms-rails#7]
Just ran into an issue in production where we need the [redis_ssl data store adapter](https://github.com/ButterCMS/buttercms-ruby/commit/074646e69d9af151202f936197c20c02c71b3424). But this this gem has that version locked to `~> 2.0.0`. Can we get the buttercms-ruby version up to the latest 2.4.0?

**Comment by ViolanteCodes** [comment]
Hi @mark-kraemer - this repo has been sunset per the readme.

For the new rails starter, you can look here: https://github.com/butterCMS/rails-starter-buttercms/

We have the ruby gem here: https://github.com/butterCMS/buttercms-ruby/
​
Or you are welcome to fork and update the package as you like.
